=== KD377/My-Projects/HTML_XML_CSS_JS_SVG/zoo.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.XMLTechnologies.org/zoo"
            elementFormDefault="qualified"
            xmlns:z="http://www.XMLTechnologies.org/zoo">

  <xsd:element name="zoo" type="z:zooType">

    <xsd:key name="key_idG">
      <xsd:selector xpath="./z:gatunki/z:gatunek"/>
      <xsd:field xpath="@idG"/>
    </xsd:key>

    <xsd:key name="key_idWybiegu">
      <xsd:selector xpath="./z:wybiegi/z:wybieg"/>
      <xsd:field xpath="@idWybiegu"/>
    </xsd:key>

    <xsd:keyref name="keyref_idG" refer="z:key_idG">
        <xsd:selector xpath="./z:zwierzeta/z:zwierze"/>
        <xsd:field xpath="@idG"/>
    </xsd:keyref>

    <xsd:keyref name="keyref_idWybiegu" refer="z:key_idWybiegu">
        <xsd:selector xpath="./z:zwierzeta/z:zwierze"/>
        <xsd:field xpath="@idWybiegu"/>
    </xsd:keyref>

  </xsd:element>

  <xsd:complexType name="zooType">
    <xsd:all>
      <xsd:element name="header" type="z:headerType"/>
      <xsd:element name="zwierzeta" type="z:animalsType"/>
      <xsd:element name="wybiegi" type="z:wybiegiType"/>
      <xsd:element name="gatunki" type="z:gatunkiType"/>
    </xsd:all>
  </xsd:complexType>

  <xsd:complexType name="headerType">
    <xsd:sequence>
      <xsd:element name="autor" type="z:autorType"/>
      <xsd:element name="nrIndeksu" type="z:indexType"/>
      <xsd:element name="dataModyfikacji" type="xsd:date"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="autorType">
    <xsd:list itemType="z:autorStringType"/>
  </xsd:simpleType>

  <xsd:simpleType name="autorStringType">
    <xsd:restriction base="xsd:string">
      <xsd:maxLength value="20"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="indexType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9]"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="animalsType">
    <xsd:sequence>
      <xsd:element name="zwierze" type="z:animalType" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="animalType">
    <xsd:sequence>
      <xsd:group ref="z:animalGroup"/>
    </xsd:sequence>
    <xsd:attribute name="idG" type="z:idGType"/>
    <xsd:attribute name="idWybiegu" type="z:idWybieguType"/>
    <xsd:attribute name="class" type="z:classType"/>
  </xsd:complexType>

  <xsd:simpleType name="classType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="1"/>
      <xsd:enumeration value="2"/>
      <xsd:enumeration value="3"/>
      <xsd:enumeration value="4"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:group name="animalGroup">
    <xsd:sequence>
      <xsd:element name="nazwaZwierzecia" type="z:nazwaType"/>
      <xsd:element name="imie" type="z:nazwaType" />
      <xsd:choice>
        <xsd:element name="wiek" type="z:wiekType"/>
      </xsd:choice>
      <xsd:element name="waga" type="z:wagaType"/>
      <xsd:element name="zdjecie" type="z:zdjecieType" />
      <xsd:element name="dataUrodzenia" type="z:dataType"/>
    </xsd:sequence>
  </xsd:group>

  <xsd:simpleType name="nazwaType">
    <xsd:restriction base="xsd:string">
      <xsd:maxLength value="15"/>
      <xsd:whiteSpace value="preserve"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="wiekType">
    <xsd:restriction base="xsd:integer">
      <xsd:minInclusive value="0"/>
      <xsd:maxInclusive value="300"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="wagaType">
    <xsd:simpleContent>
      <xsd:extension base="z:wagaintType">
        <xsd:attribute name="jednostka" type="z:jednostkaType"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:simpleType name="wagaintType">
    <xsd:restriction base="xsd:decimal">
      <xsd:maxInclusive value="1000"/>
      <xsd:minInclusive value="0"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="zdjecieType">
    <xsd:attribute name="src" type="z:sourceType" use="required"/>
    <xsd:attribute name="format" type="z:formatType" use="required"/>
  </xsd:complexType>

  <xsd:simpleType name="sourceType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="./Photos/Animals/.*" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="formatType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="JPEG"/>
      <xsd:enumeration value="PNG"/>
      <xsd:enumeration value="GIF"/>
    </xsd:restriction>
  </xsd:simpleType>


  <xsd:simpleType name="dataType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[0-9][0-9].[0-9][0-9].[0-9][0-9][0-9][0-9]"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="wybiegiType">
    <xsd:sequence>
      <xsd:element name="wybieg" type="z:wybiegType" maxOccurs="30"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="wybiegType">
    <xsd:sequence>
      <xsd:group ref="z:wybiegGroup"/>
    </xsd:sequence>
    <xsd:attribute name="idWybiegu" type="z:idWybieguType" use="required"/>
  </xsd:complexType>

  <xsd:group name="wybiegGroup">
    <xsd:sequence>
      <xsd:element name="sektor" type="z:sektorType"/>
      <xsd:element name="powierzchnia" type="z:powierzchniaType"/>
      <xsd:element name="typ" type="z:typType"/>
    </xsd:sequence>
  </xsd:group>

  <xsd:simpleType name="sektorType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="A"/>
      <xsd:enumeration value="B"/>
      <xsd:enumeration value="C"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="powierzchniaType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:nonNegativeInteger">
        <xsd:attribute name="jednostka" type="z:jednostkaType"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:simpleType name="jednostkaType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="m^2"/>
      <xsd:enumeration value="kg"/>
      <xsd:maxLength value="3"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="typType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="otwarty"/>
      <xsd:enumeration value="zamkniÄ™ty"/>
      <xsd:enumeration value="wodny"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="gatunkiType">
    <xsd:sequence>
      <xsd:element name="gatunek" type="z:gatunekType" maxOccurs="5"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="gatunekType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="idG" type="z:idGType" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:simpleType name="idGType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[0-9][0-9]" />
      <xsd:maxLength value="2" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="idWybieguType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="W[0-2][0-9]"/>
      <xsd:maxLength value="3"/>
    </xsd:restriction>
  </xsd:simpleType>


</xsd:schema>

=== KD377/My-Projects/HTML_XML_CSS_JS_SVG/zoo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/css" href="zoo.css"?>
  <z:zoo
    xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
    xsd:schemaLocation="http://www.XMLTechnologies.org/zoo zoo.xsd"
    xmlns:z="http://www.XMLTechnologies.org/zoo" >

    <z:header>
      <z:autor>Autorem dokumentu jest Krzysztof Deka</z:autor>
      <z:nrIndeksu>242377</z:nrIndeksu>
      <z:dataModyfikacji>2022-11-07</z:dataModyfikacji>
    </z:header>
    <z:zwierzeta>

      <z:zwierze idG="01" idWybiegu="W01" class="1">
        <z:nazwaZwierzecia >Słoń</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Stefan</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>22</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">500.0</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>12.05.2000</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->
      </z:zwierze>

      <z:zwierze idG="01" idWybiegu="W02" class="2">
        <z:nazwaZwierzecia >Wydra</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Zosia</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>15</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">20.0</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>12.05.2007</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->
      </z:zwierze>
      <z:zwierze idG="01" idWybiegu="W03" class="3">
        <z:nazwaZwierzecia >Pingwin</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Kowalski</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>2</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">75.0</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>13.04.2020</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->
      </z:zwierze>
      <z:zwierze idG="01" idWybiegu="W04" class="4">
        <z:nazwaZwierzecia >Żyrafa</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Agata</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>5</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">450.0</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>01.06.2017</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->
      </z:zwierze>
      <z:zwierze idG="04" idWybiegu="W05" class="1">
        <z:nazwaZwierzecia >Płaszczka</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Cecylia</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>16</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">200.0</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>19.12.2006</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->
      </z:zwierze>
      <z:zwierze idG="01" idWybiegu="W06" class="2">
        <z:nazwaZwierzecia >Koń</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Adrian</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>1</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">500.0</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>01,01.2021</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->
      </z:zwierze>
      <z:zwierze idG="02" idWybiegu="W07" class="3">
        <z:nazwaZwierzecia >Salamandra</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Weri</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>2</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">0.2</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>17.07.2020</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->
      </z:zwierze>
      <z:zwierze idG="03" idWybiegu="W08" class="4">
        <z:nazwaZwierzecia >Żaba</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Lucy</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>3</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">0.1</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>12.05.2019</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->

      </z:zwierze>
      <z:zwierze idG="01" idWybiegu="W09" class="1">
        <z:nazwaZwierzecia >Lew</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Daro</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>7</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">650.0</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>02.09.2016</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->

      </z:zwierze>
      <z:zwierze idG="01" idWybiegu="W10" class="2">
        <z:nazwaZwierzecia >Tygrys</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Michał</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>10</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">700.0</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>14.02.2012</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->

      </z:zwierze>
      <z:zwierze idG="01" idWybiegu="W11" class="3">
        <z:nazwaZwierzecia >Kapucynka</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Stefcia</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>3</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">30.0</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>12.05.2019</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->

      </z:zwierze>
      <z:zwierze idG="04" idWybiegu="W12" class="4">
        <z:nazwaZwierzecia >Pirania</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Ada</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>2</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">0.7</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>26.05.2020</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->

      </z:zwierze>
      <z:zwierze idG="01" idWybiegu="W13" class="1">
        <z:nazwaZwierzecia >Koza</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Adrian</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>5</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">150.0</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>11.11.2017</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->

      </z:zwierze>
      <z:zwierze idG="05" idWybiegu="W14" class="2">
        <z:nazwaZwierzecia >Paw</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Burek</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>3</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">50.0</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
        <z:zdjecie src="./Photos/Animals/Stefan" format="JPEG"/><!--zdjęcie musi byc zapisane pod podaną ścieżką w formacie JPEG-->
        <z:dataUrodzenia>12.05.2019</z:dataUrodzenia><!-- data w formacie dd.mm.yyyy-->

      </z:zwierze>
      <z:zwierze idG="05" idWybiegu="W15" class="3">
        <z:nazwaZwierzecia >Bażant</z:nazwaZwierzecia> <!--nazwa może zawierać 40 znaków  -->
        <z:imie >Beza</z:imie><!--Imie zaczyna się wielką literą i może zaiwerać max 15 znaków-->
        <z:wiek>12</z:wiek><!-- liczba całkowita -->
        <z:waga jednostka="kg">12.0</z:waga><!--liczba zmiennoprzecinowa. Reprezentacja w jednostce kg -->
